# Generated by Django 5.2.12 on 2026-05-05 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Discord ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_discord_verified',
            field=models.BooleanField(default=False, verbose_name='Discord підтверджено'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_tg_verified',
            field=models.BooleanField(default=False, verbose_name='Telegram підтверджено'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.CreateModel(
            name='SocialAccountValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord')], max_length=20)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_validations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
