# Generated by Django 6.0.3 on 2026-04-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_alter_announcement_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tournament.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Запрошення в команду',
                'verbose_name_plural': 'Запрошення в команду',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('team', 'email'), name='unique_invitation_email_per_team')],
            },
        ),
    ]
