# Generated by Django 6.0.3 on 2026-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_tournament_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на зовнішній шаблон'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на зовнішній банер'),
        ),
    ]
