# Generated by Django 5.2.12 on 2026-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_certificatetemplate_background_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Назва навчального закладу')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Скорочена назва (опціонально)')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Місто/Населений пункт')),
            ],
            options={
                'verbose_name': 'Навчальний заклад',
                'verbose_name_plural': 'Навчальні заклади',
                'ordering': ['name'],
            },
        ),
    ]
