# Generated by Django 6.0.3 on 2026-05-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_certificatetemplate_background_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Чернетка'),
        ),
    ]
