# Generated by Django 5.2.12 on 2026-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=500, verbose_name='Місто/Населений пункт'),
        ),
        migrations.AlterField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Скорочена назва (опціонально)'),
        ),
    ]
