# Generated by Django 5.2.12 on 2026-05-04 19:19

import tournament.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_alter_school_city_alter_school_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[tournament.models.validate_team_school], verbose_name='Школа'),
        ),
    ]
