# Generated by Django 5.2.12 on 2026-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_alter_team_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='viber',
        ),
        migrations.AlterField(
            model_name='team',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('telegram', 'Телеграм'), ('discord', 'Діскорд')], max_length=20, null=True, verbose_name="Спосіб зв'язку"),
        ),
    ]
