# Generated by Django 5.2.12 on 2026-05-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_alter_task_is_draft'),
        ('tournament', '0031_remove_team_viber_and_more'),
    ]

    operations = [
    ]
