# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва шаблону')),
                ('image', models.ImageField(upload_to='banner_templates/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон банера',
                'verbose_name_plural': 'Шаблони банерів',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_banners/', verbose_name='Банер турніру (власний)'),
        ),
    ]
