# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0034_bannertemplate_tournament_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='banner_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tournaments',
                to='tournament.bannertemplate',
                verbose_name='Шаблонний банер',
            ),
        ),
    ]
