# Generated by Django 6.0.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0034_bannertemplate_tournament_banner_image'),
        ('tournament', '0035_tournament_banner_template'),
    ]

    operations = [
    ]
